The dataset we are looking at is the measure of 10000 customers of a bank with 
- CustomerId, 
- Surname, 
- CreditScore, 
- Geography, 
- Gender, 
- Age, 
- Tenure(how long the customer has been with the bank), 
- Balance(balance of the customer at that point when the data was loaded), 
- NoOfProducts(no of produts the customer had like savings account,credit card,loan),- 
- HasCrCard(did the customer has a credit card or not), 
- IsActiveMember(is the customer an active member), 
- EstimatedSalary(estimated salary of the customer), 
- Exited(whether the person left the bank within 6 months).



In [1]:
import keras 

Using TensorFlow backend.


In [0]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
!wget https://www.dropbox.com/s/t9uil3kvmv0ypbv/Churn_Modelling.csv

--2018-11-28 01:16:23--  https://www.dropbox.com/s/t9uil3kvmv0ypbv/Churn_Modelling.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.8.1, 2620:100:601b:1::a27d:801
Connecting to www.dropbox.com (www.dropbox.com)|162.125.8.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/t9uil3kvmv0ypbv/Churn_Modelling.csv [following]
--2018-11-28 01:16:23--  https://www.dropbox.com/s/raw/t9uil3kvmv0ypbv/Churn_Modelling.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc5058c155d87bf736a62077df06.dl.dropboxusercontent.com/cd/0/inline/AWbf2J5HH40TJfxTGTDifpJoHgmWS2oystluJH76h2Dp8_tRGRgYehrNbqUKvjK9yDBzb_0jR7Ow4AvNi1joZscQgkvIskIM8TcxsR15l0pjNxXqmC_PX5AnGP2FU2eYYHaDykOpCGVA7Bd92srouqHUyE1-MiUca6-cTIp1FkTnC3_L4XjPLq6dPMUW20L5jXM/file [following]
--2018-11-28 01:16:24--  https://uc5058c155d87bf736a62077df06.dl.dropboxusercontent.com/cd/0/inline/AWbf2J5HH40TJfxTGTDifpJoHgmWS2

In [4]:
ls -l

total 2180
-rw-r--r-- 1 root root  684858 Nov 28 01:16 Churn_Modelling.csv
-rw-r--r-- 1 root root 1423529 Nov 28 01:08 housing.csv
-rw-r--r-- 1 root root    3320 Nov 28 01:13 my_model.pkl
-rw-r--r-- 1 root root   28629 Nov 28 00:57 production.csv
-rw-r--r-- 1 root root    2839 Nov 28 00:57 result.csv
drwxr-xr-x 2 root root    4096 Nov 20 18:17 sample_data/
-rw-r--r-- 1 root root   60302 Nov 28 00:57 titanic.csv


In [0]:
dataset = pd.read_csv('Churn_Modelling.csv')


In [6]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [0]:
X = dataset.iloc[:, 3:13].values # pick from index 3 (CreditScore - EstimateSalary) not included Exited index13
y = dataset.iloc[:, 13].values

In [9]:
X.shape

(10000, 10)

In [10]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [11]:
y[0]

1

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [0]:
labelencoder = LabelEncoder()

In [14]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [15]:
X[:,1]  #all rows and take one column

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [16]:
set(X[:,1])  #looking at possible values ( France, Germany .... ) // displays Unique Values 

{'France', 'Germany', 'Spain'}

In [0]:
X[:, 1] = labelencoder.fit_transform(X[:, 1]) # taking all the values at column 1st(2nd column) , take values at 0 1 and 2 and put it back into the column 1 

In [18]:
X[0]

array([619, 0, 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [19]:
X[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [20]:
set(X[:,1])

{0, 1, 2}

In [21]:
X[:,2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [22]:
set(X[:,2])

{'Female', 'Male'}

In [0]:
X[:, 2] = labelencoder.fit_transform(X[:, 2])

In [24]:
X[0]

array([619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [25]:
X[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [26]:
set(X[:,2])

{0, 1}

In [0]:
onehotencoder = OneHotEncoder(categorical_features = [1]) # for the 1 represents 1st column 

In [28]:
X[0]

array([619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [0]:
X = onehotencoder.fit_transform(X).toarray() 

In [30]:
type(X)

numpy.ndarray

In [31]:
X[0]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [0]:
X = X[:, 1:]

In [33]:
X[0] 

array([0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
sc = StandardScaler()  # standardize to mean and variance -> mean become = 0 and standard deviation = 1 

In [0]:
X_train = sc.fit_transform(X_train) # sc 

In [39]:
np.std(X_train[:,2])

0.9999999999999841

In [40]:
X_train[0]

array([-0.5698444 ,  1.74309049,  0.16958176, -1.09168714, -0.46460796,
        0.00666099, -1.21571749,  0.8095029 ,  0.64259497, -1.03227043,
        1.10643166])

In [0]:
X_test = sc.transform(X_test) # uses the scaling factors used in X_train above. So only transform must be done. No Fitting

In [0]:
#Now lets make ANN

In [0]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
# Initialising the ANN
classifier = Sequential()

In [45]:
X_train.shape

(8000, 11)

In [0]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 9, kernel_initializer = 'uniform', 
                     activation = 'relu', input_dim = 11))

In [0]:
# Adding the second hidden layer
classifier.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'relu'))

In [0]:
# Adding the third hidden layer
classifier.add(Dense(units = 8, kernel_initializer = 'uniform', activation = 'relu'))

In [0]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [0]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [51]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 9)                 108       
_________________________________________________________________
dense_2 (Dense)              (None, 10)                100       
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 9         
Total params: 305
Trainable params: 305
Non-trainable params: 0
_________________________________________________________________


In [52]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 2000, epochs = 20)


Epoch 1/20
8000/8000 [==============================] - 2s 291us/step - loss: 0.6927 - acc: 0.7380
Epoch 2/20
8000/8000 [==============================] - 0s 5us/step - loss: 0.6915 - acc: 0.7960
Epoch 3/20
8000/8000 [==============================] - 0s 5us/step - loss: 0.6901 - acc: 0.7960
Epoch 4/20
8000/8000 [==============================] - 0s 4us/step - loss: 0.6887 - acc: 0.7960
Epoch 5/20
8000/8000 [==============================] - 0s 5us/step - loss: 0.6871 - acc: 0.7960
Epoch 6/20
8000/8000 [==============================] - 0s 5us/step - loss: 0.6855 - acc: 0.7960
Epoch 7/20
8000/8000 [==============================] - 0s 5us/step - loss: 0.6838 - acc: 0.7960
Epoch 8/20
8000/8000 [==============================] - 0s 5us/step - loss: 0.6820 - acc: 0.7960
Epoch 9/20
8000/8000 [==============================] - 0s 5us/step - loss: 0.6800 - acc: 0.7960
Epoch 10/20
8000/8000 [==============================] - 0s 5us/step - loss: 0.6777 - acc: 0.7960
Epoch 11/20
8000/8000 [====

In [0]:
#Part 3 - Making predictions and evaluating the model

In [0]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [55]:
new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)
new_prediction

array([[False]])

In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [57]:
cm

array([[1595,    0],
       [ 405,    0]])